### ISSUE TITLE
Domain get_info raises exception in objects.py

### ISSUE THREAD

**Issue by alexraileanu** [benkonrath/transip-api#28]
when trying to get the info of a certain domain, there's an exception raised in the objects.py file. investigating i saw it's caused because on the line 51 in the `__eq__` function, sometimes there's lists passed as the `other` variable and the checks fail.

my code:

```
import transip

from transip.service.domain import DomainService
from transip.service.objects import DomainCheckResult

client = DomainService(login='user', private_key_file='./private.key')

domain = 'domain.com'

print(client.get_info(domain))
```

full stack trace:

```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    print(client.get_info(domain))
  File "/tmp/transip-test/venv/lib/python3.6/site-packages/suds/__init__.py", line 166, in <lambda>
    __str__ = lambda x: x.__unicode__()
  File "/tmp/transip-test/venv/lib/python3.6/site-packages/suds/sudsobject.py", line 172, in __unicode__
    return self.__printer__.tostr(self)
  File "/tmp/transip-test/venv/lib/python3.6/site-packages/suds/sudsobject.py", line 256, in tostr
    return self.process(object, history, indent)
  File "/tmp/transip-test/venv/lib/python3.6/site-packages/suds/sudsobject.py", line 265, in process
    return self.print_object(object, h, n+2, nl)
  File "/tmp/transip-test/venv/lib/python3.6/site-packages/suds/sudsobject.py", line 312, in print_object
    s.append(self.process(item[1], h, n, True))
  File "/tmp/transip-test/venv/lib/python3.6/site-packages/suds/sudsobject.py", line 273, in process
    return self.print_collection(object, h, n+2)
  File "/tmp/transip-test/venv/lib/python3.6/site-packages/suds/sudsobject.py", line 352, in print_collection
    s.append(self.process(item, h, n-2))
  File "/tmp/transip-test/venv/lib/python3.6/site-packages/suds/sudsobject.py", line 265, in process
    return self.print_object(object, h, n+2, nl)
  File "/tmp/transip-test/venv/lib/python3.6/site-packages/suds/sudsobject.py", line 282, in print_object
    if d in h:
  File "/tmp/transip-test/venv/lib/python3.6/site-packages/transip/service/objects.py", line 57, in __eq__
    return self.name == other.name and self.type == other.type and self.content == other.content
AttributeError: 'list' object has no attribute 'name'
```

**Comment by benkonrath** [comment]
Thanks for reporting this bug. It should be fixed now. I'll try to make a new release soon.
